# Generated by Django 4.0.4 on 2022-05-27 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('detailsid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MasterCategory',
            fields=[
                ('masterid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('modeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('transid', models.AutoField(primary_key=True, serialize=False)),
                ('transdate', models.DateField()),
                ('transsubdetails', models.CharField(max_length=100)),
                ('transamount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('transcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailytrans.mastercategory')),
                ('transdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailytrans.details')),
                ('transmode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dailytrans.paymentmode')),
            ],
        ),
    ]
